name: Upload data

on:
  push:
    branches: master

jobs:
  upload:
    runs-on: ubuntu-latest


    steps: 
      -name: Get the Coverage info
       run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
